### ISSUE TITLE
Navigation between pages shows blank screen

### ISSUE THREAD

**Issue by vijayk036** [godesign/nativeDroid2#13]
Hi ,

I have noticed a strange behavior in Nativedroid2, if you navigate between pages with anchor tag, next page content hides by default only white screen is visible.
This behavior is because of setting of opacity value to 0, this is done by the code below(resides in nativedroid2.js)

	$(document).on("pagechange",function(){
		$("body").removeClass("nd2-ready");
	});
for now I have commented  removeClass code, and navigation works perfectly, could you please let me know why are you removing nd2-ready on pagechange, is there any other side effect of removing this code.

regards,
Vijay.

**Comment by godesign** [comment]
Hi Vijay,

I've done this very experimentally for a smooth page transition wich goes from opacity: 0 to 1 when page loads.

I've just removed the opacity: 0; in body style and this is fixed now.
```css
body { opacity: 0; }```

Regards,
Raphael

fixed in commit:
https://github.com/godesign/nativeDroid2/commit/698f0006b6b07f568329dd61e6e467e24f8d045d#diff-62c776f96700263cca315a5abf74a52cL30

**Comment by vijayk036** [comment]
Hi godesign,

Thanks for your quick reply.

Regards,
Vijay
