### ISSUE TITLE
nativedroid footer menu items has issue with ie8 and ie9

### ISSUE THREAD

**Issue by minamorsali** [godesign/nativeDroid2#25]
Hello and many thanks for nativedroid very good and nice mobile design. native droid footer menus has issue in ie9 and ie8 and not show correctly. I upload an image that show the problem.
![aaa](https://cloud.githubusercontent.com/assets/10794508/9026943/5c3be290-3957-11e5-8c50-ca0c517f7b94.png)

**Comment by godesign** [comment]
Well, I'm using flexbox as grid system (http://caniuse.com/#feat=flexbox) IE9 and lower does not support that at all.

If you really need support for these two dinosaures-browser in a mobile environment (??), you can easily rebuild that adjusting the grid that wraps the buttons here; https://github.com/godesign/nativeDroid2/blob/master/examples/elements/header_footer.html#L48 and https://github.com/godesign/nativeDroid2/blob/master/examples/fragments/bottom.sheet.html

Because nativeDroid2 should stay a forward-thinking jQueryMobile template (for mobile environment), I dont think about fixing for that 6 or 4 year old lousy browsers, sorry.
