### ISSUE TITLE
nd2-include is not working properly

### ISSUE THREAD

**Issue by sujeetqustn** [godesign/nativeDroid2#28]
I am using nativeDroid2 for my cordova apps. The UI is really awesome.
But i am facing a problem:
```javascript
<nd2-include data-src="/examples/fragments/panel.left.html"></nd2-include>
```
I am using the above line to include panel in my app, But it throws an error. Please help:
please see the error message::
```javascript
XMLHttpRequest cannot load file:///D:/examples/fragments/panel.left.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by godesign** [comment]
The Error Message tells you everything you have to know.

Ajax-Requests are not allowed when you use the "file://"-Protocol. Thats not a bug in nd2-include. Instead of using nd2-include you have to add the content at the right place.

The following thread can help you how to overcome this behaviour:
https://forum.jquery.com/topic/how-do-i-get-ajax-working-with-phonegap

**Comment by phamvansy** [comment]
XAMPP 503 Error when directory named "examples".
I confirm the same behaviour for Drupal 7 on XAMPP 1.7.4 even without TomCat installed:
the parts of Examples module end up showing "Service unavailable!" error bacause of the preconfigured redirect.

To fix it navigate to file:
C:\xampp\apache\conf\extra\httpd-ajp.conf
and comment out the following line with #:
ProxyPass /examples ajp://127.0.0.1:8009/examples smax=0 ttl=60 retry=5
Then restart the server and enjoy these great Examples.
