### ISSUE TITLE
Multiple nd2tabs not working properly

### ISSUE THREAD

**Issue by radzik07** [godesign/nativeDroid2#36]
Hi,
there's a problem I can't figure out.
I have two pages: "pageOne" and "pageTwo".
Each page has nd2tabs implemented.
Now, I go to pageOne and select tab2, then I go to pageTwo and select tab3.
When I go back to pageOne, the tab2 is selected, but there's no content visible.
I have to click on other tab and then on tab2 to see it back there.
Same happens, when I switch now to pageTwo.

**Comment by godesign** [comment]
I just made a change to the tabs-plugin. It now checks the tab-content only on the "page"-Scope instead of the "body"-Scope before.

Because I could not check this locally. Please let me know if it works now.

Thanks.

**Comment by Tumke** [comment]
I still have this problem. The bug is not resolved. I also use multiple tabs on different pages in one JQM page. The first  page with tabs works fine, but when you go to the second page with tabs none of the tabs are active. When clicking on a tab it's not showing any content. After a second click he shows the content. I tried to make the tabnames unique for each page but thats not resolving the problem. Can you please look again to this problem? thanks

**Comment by ntym4ek** [comment]
The problem is much more complex, than "page" and "body" scopes issue.
Different Tabs instances at same or different pages have common settings. Also it has poor coding, when all tabs in the DOM collecting at one array to define which one is active.
I attached my version of Tabs widget at issue #108
