### ISSUE TITLE
Bug in waves-effect

### ISSUE THREAD

**Issue by rcpinheiro** [godesign/nativeDroid2#49]
I found a bug in the waves-effect CSS.

Here's a very simple page to that shows the problem:

```
<div data-role="page">
<div data-role="header" data-position="fixed">... some header ...</div>
<div id="mycontent">
<ul data-role="nd2tabs" data-swipe="false">
  <li data-tab="f1" data-tab-active="true">Tab 1</li>
  <li data-tab="f2">Tab 2</li>
  <li data-tab="f3">Tab 3</li>
  <li data-tab="f4">Tab 4</li>
</ul>

<div data-role="nd2tab" data-tab="f1">... tab 1...</div>
<div data-role="nd2tab" data-tab="f2">... tab 2...</div>
<div data-role="nd2tab" data-tab="f3">... tab 3...</div>
<div data-role="nd2tab" data-tab="f4">... tab 4...</div>

</div><!-- mycontent -->

<div data-role="footer" data-position="fixed">... some footer ...</div>
```

First of all, there's an extra 5px at the bottom of the tab selector that ruins the design.
But, most importantly, changing tabs sometimes generate a scrollbar on the page (but not always).
I've tracked down the problem to the waves-effect css. If I remove _overflow:hidden_ then these problems go away but then appears a scrollbar on the tab selector for a short time.

Here's an image to illustrate the problems:
http://i.imgur.com/hZyKD3J.png

**Comment by rcpinheiro** [comment]
Please note that the problem can be minimized using **data-tap-toggle** on the footer. I.e. '<div data-role="footer" data-position="fixed" data-tap-toggle="false">`

**Comment by godesign** [comment]
This issue could be fixed in several way's with different consequences:
1. floating the tabs and remove the -5px margin-bottom would work but leads in a multi-line-view of the tabs if the "overflow"
2. fixing the height to the parent's height (48px) and set the overflow of the Y-Axis to hidden works as expected but leads into the issue, that in some OS the scrollbar overlaps the tabs a bit.

Because this theme will be mostly used for Mobile Devices and desktop screen resolutions are usually wider than the tab-list I decided to fix this with the second solution.

Any other inputs are welcome.
