### ISSUE TITLE
Toast appear under the footer

### ISSUE THREAD

**Issue by joseluisvl** [godesign/nativeDroid2#50]
Hi,
I have noticed than when you use a toast and you have a page with a footer, the toast message appears behind the footer, so you cannot read the content.

Thanks.

Regards, Jose.

**Comment by DjEmet** [comment]
I experienced the same issue. For now, i solved it simply by changing the toast bottom-margin and the z-index through custom css. It's a quickly raw fix, the problem is that with this rule it lost the native animation. It should be necessary to add a little snippet (maybe via jquery) to fix it or a more better solution.

**Comment by godesign** [comment]
Thanks you for the ticket. I just solved this by adjusting the the Toast's z-index. I think its a quick and performant way to fix it.
